In [1]:
import numpy as np

In [2]:
import torch

In [3]:
import scipy.sparse as sp

In [4]:
import os

In [5]:
for file in os.listdir():
    print(file)

.git
.idea
.ipynb_checkpoints
About dist data
amazon_electronics_computers.npz
args.py
A_sp.npz
citeseer.edges
citeseer.node_labels
data
dataset.py
datasets
data_arrays_link.npz
dists-1.dat
dists.txt
dist_graph.gexf
EDGES.txt
edge_samples.txt
FEATURES.txt
ind.citeseer.x
ind_train_A.npz
ind_train_X.npz
LICENSE
model.py
MSC_FEE_4TH_SEM.pdf
nodes_hide.npy
nodes_keep.npy
Prepare Data for DEAL.ipynb
Preparing data for DEAL
pv0.10_pt0.00_pn0.10_arrays.npz
README.md
sample_graph.gexf
Studying Data Files.ipynb
train.py
Untitled.ipynb
utils.py
X_sp.npz
z.npy
__pycache__


# List of files used in the program

- A_sp.npz
- data_arrays_link.npz
- ind_train_A.npz
- ind_train_X.npz
- nodes_hide.npy
- nodes_keep.npy
- pv0.10_pt0.00_pn0.10_arrays.npz
- X_sp.npz
- z.npy

## A_sp.npz

In [6]:
#npz implies numpy zip files

In [7]:
A = sp.load_npz('A_sp.npz')

In [8]:
A

<3327x3327 sparse matrix of type '<class 'numpy.float64'>'
	with 4552 stored elements in Compressed Sparse Row format>

In [9]:
#print the matrix A
A.toarray(),A.toarray().shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 (3327, 3327))

In [10]:
A.toarray()[2,3285]

1.0

In [11]:
#The shape implies that the dataset contains 3327 nodes

In [12]:
A.nonzero()

(array([   0,    1,    1, ..., 3301, 3319, 3322]),
 array([ 628,  158,  486, ..., 3302, 3320, 3323]))

In [13]:
#Let's try to print the edges
'''
size_A = A.toarray().shape
A_mat = A.toarray()
edge_count = 0
for i in range(size_A[0]):
    for j in range(size_A[1]):
        if A_mat[i][j] == 1.0:
            edge_count = edge_count + 1
            print(str(i) + ',' + str(j))
'''

"\nsize_A = A.toarray().shape\nA_mat = A.toarray()\nedge_count = 0\nfor i in range(size_A[0]):\n    for j in range(size_A[1]):\n        if A_mat[i][j] == 1.0:\n            edge_count = edge_count + 1\n            print(str(i) + ',' + str(j))\n"

In [14]:
#print("The network corresponding to matrix A contains "+str(edge_count)+" edges.")

## X_sp.npz

In [15]:
X = sp.load_npz('X_sp.npz')

In [16]:
#print the matrix X
X.toarray(),X.toarray().shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 (3327, 3703))

In [17]:
#X matrix contains the features of the nodes
#the size of the matrix is (3327,3703) that means there are 3327 nodes and each node has a feature of length 3703

## pv0.10_pt0.00_pn0.10_arrays.npz

In [18]:
#this file contains multiple matrices/arrays corresponding to train_ones, val_ones, val_zeros, test_ones, test_zeros

p = np.load('pv0.10_pt0.00_pn0.10_arrays.npz')
train_ones,val_ones, val_zeros, test_ones, test_zeros = p.values()

In [19]:
len(val_ones)/len(train_ones)

0.11134708737864078

In [20]:
train_ones,train_ones.shape

(array([[1171, 2018],
        [1368, 2557],
        [1205, 2399],
        ...,
        [2762, 2784],
        [2816, 2817],
        [2819, 2820]]),
 (3296, 2))

In [21]:
#return unique elements in 2-D array
def get_unique_2D(data):
    nodes_list = []
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            nodes_list.append(data[i][j])
    
    nodes_list = list(set(nodes_list))
    return nodes_list

In [22]:
#Let's find the list of nodes present in the file

nodes_list = get_unique_2D(train_ones)
len(nodes_list)

2824

In [23]:
val_ones.shape[0]

367

In [24]:
val_zeros.shape[0]

367

## ind_train_A.npz

In [25]:
a_train = sp.load_npz('ind_train_A.npz')

In [26]:
a_train

<2824x2824 sparse matrix of type '<class 'numpy.float64'>'
	with 3663 stored elements in Compressed Sparse Row format>

In [27]:
a_train.toarray(),a_train.toarray().shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 (2824, 2824))

In [28]:
a_train.toarray()[1242][2753]

1.0

In [29]:
'''
size_A = a_train.toarray().shape
A_mat = a_train.toarray()
edge_count = 0
for i in range(size_A[0]):
    for j in range(size_A[1]):
        if A_mat[i][j] == 1.0:
            edge_count = edge_count + 1
            print(str(i) + ',' + str(j))
'''

"\nsize_A = a_train.toarray().shape\nA_mat = a_train.toarray()\nedge_count = 0\nfor i in range(size_A[0]):\n    for j in range(size_A[1]):\n        if A_mat[i][j] == 1.0:\n            edge_count = edge_count + 1\n            print(str(i) + ',' + str(j))\n"

In [30]:
#that means ind_A_train contains information about edges of these 2824 particular nodes

## ind_train_X.npz

In [31]:
x_train = sp.load_npz('ind_train_X.npz')

In [32]:
x_train

<2824x3703 sparse matrix of type '<class 'numpy.float32'>'
	with 89403 stored elements in Compressed Sparse Row format>

In [33]:
x_train.toarray() , x_train.toarray().shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 (2824, 3703))

In [34]:
#ind_train_x contains features of the 2824 nodes that are used for training the model

### nodes_keep.npy

In [35]:
nodes_keep = np.unique(np.load('nodes_keep.npy'))

In [36]:
nodes_keep

array([   0,    1,    3, ..., 3324, 3325, 3326], dtype=int64)

### nodes_hide.npy

In [37]:
nodes_hides = np.unique(np.load('nodes_hide.npy'))

In [38]:
nodes_hides

array([   2,   23,   25,   37,   45,   55,   56,   70,   72,   88,  107,
        112,  115,  125,  148,  161,  169,  173,  174,  177,  185,  192,
        193,  215,  221,  223,  226,  234,  240,  243,  252,  267,  276,
        280,  293,  294,  312,  325,  339,  341,  355,  358,  359,  362,
        365,  384,  398,  410,  420,  436,  446,  450,  453,  468,  474,
        478,  485,  489,  492,  496,  498,  511,  519,  526,  540,  546,
        549,  555,  559,  563,  572,  576,  582,  583,  586,  592,  603,
        613,  625,  647,  655,  656,  665,  676,  677,  679,  708,  719,
        722,  737,  738,  747,  760,  768,  769,  783,  785,  787,  789,
        794,  798,  805,  814,  821,  822,  827,  828,  831,  834,  838,
        843,  845,  848,  855,  856,  861,  864,  870,  872,  880,  883,
        892,  896,  898,  899,  905,  908,  909,  910,  913,  922,  926,
        930,  937,  939,  944,  949,  957,  965,  967,  973,  979,  983,
       1006, 1014, 1015, 1024, 1025, 1028, 1029, 10

In [39]:
for i in nodes_hides:
    np.append(nodes_keep,i)

In [40]:
len(list(set(nodes_keep)))

2824

## make test_edges and val_edges

In [41]:
test_edges = np.row_stack((test_ones, test_zeros))
val_edges = np.row_stack((val_ones, val_zeros))

In [42]:
test_ones,test_zeros

(array([[   2, 3285],
        [  12,  677],
        [  12,  794],
        ...,
        [3146, 3147],
        [3228, 3236],
        [3286, 3287]], dtype=int64),
 array([[3156, 1549],
        [3156, 1080],
        [3156, 3148],
        ...,
        [3287, 1287],
        [3313,  888],
        [3316, 1874]], dtype=int64))

In [43]:
gt_labels = A[test_edges[:, 0], test_edges[:, 1]].A1

In [44]:
test_edges[:,0],test_edges[:,1]

(array([   2,   12,   12, ..., 3287, 3313, 3316], dtype=int64),
 array([3285,  677,  794, ..., 1287,  888, 1874], dtype=int64))

In [45]:
val_ones , val_zeros

(array([[2016, 2018],
        [1242, 2753],
        [1747, 2020],
        [  52, 1205],
        [ 663, 1917],
        [ 326, 1678],
        [ 923, 1135],
        [  24, 1709],
        [ 724, 1506],
        [1805, 1933],
        [ 810, 2021],
        [ 558, 2182],
        [1260, 1789],
        [1426, 2084],
        [2238, 2553],
        [1205, 1749],
        [2110, 2210],
        [1568, 1615],
        [1197, 2010],
        [ 609, 1425],
        [ 745, 2795],
        [ 435, 1371],
        [2104, 2400],
        [1205, 2256],
        [  39, 1489],
        [ 394, 2259],
        [ 388, 2303],
        [ 236, 2231],
        [ 149, 2381],
        [1120, 2389],
        [  96, 1858],
        [1147, 1553],
        [ 880, 1747],
        [ 950, 2147],
        [ 663,  766],
        [ 388, 2301],
        [1882, 2250],
        [1408, 2036],
        [ 124,  938],
        [ 663,  783],
        [ 122, 1642],
        [1205, 1919],
        [1212, 1375],
        [1751, 2182],
        [1205, 2397],
        [1

In [46]:
test_ones

array([[   2, 3285],
       [  12,  677],
       [  12,  794],
       ...,
       [3146, 3147],
       [3228, 3236],
       [3286, 3287]], dtype=int64)

In [47]:
test_edges,val_edges

(array([[   2, 3285],
        [  12,  677],
        [  12,  794],
        ...,
        [3287, 1287],
        [3313,  888],
        [3316, 1874]], dtype=int64),
 array([[2016, 2018],
        [1242, 2753],
        [1747, 2020],
        ...,
        [2142, 1823],
        [2143, 1026],
        [2144, 1908]], dtype=int64))

In [48]:
def check_edge(v1,v2,arr):
    for i in range(arr.shape[0]):
        if arr[i][0] == v1 and arr[i][1] == v2:
            return True
    return False

In [49]:
len(get_unique_2D(test_edges)) , len(get_unique_2D(val_edges))

(2055, 1047)

In [50]:
gt_labels = A[test_edges[:, 0], test_edges[:, 1]].A1

In [51]:
gt_labels

array([1., 1., 1., ..., 0., 0., 0.])

In [52]:
var_x = x_train

In [53]:
def convert_sSp_tSp(var_x):
    coo = var_x.tocoo()
    values = coo.data
    indices = np.vstack((coo.row, coo.col))
    i = torch.LongTensor(indices)
    v = torch.FloatTensor(values)
    shape = coo.shape
    return torch.sparse.FloatTensor(i, v, torch.Size(shape))

In [54]:
sp_attrM = convert_sSp_tSp(x_train).to('cpu')

In [55]:
val_labels = a_train[val_edges[:, 0], val_edges[:, 1]].A1

In [56]:
val_labels

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [57]:
val_labels = a_train[val_edges[:, 0], val_edges[:, 1]].A1

In [58]:
val_labels

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [59]:
def get_train_data(A_train, batch_size,tv_edges,inductive):
    nodes = []
    labels = []
    tmp_A = A_train.tolil()
    
    nodeNum = A_train.shape[0]
    
    if not inductive:
        forbidden_Matrix = sp.lil_matrix(A_train.shape)
        forbidden_Matrix[tv_edges[:,0],tv_edges[:,1]] = 1
        while True:
            a = random.randint(0,nodeNum-1)
            b = random.randint(0,nodeNum-1)
            if not(forbidden_Matrix[a,b]):
                nodes.append([a,b])
                if tmp_A[a,b]:
                    labels.append(1)
                else:
                    labels.append(0)

            if len(tmp_A.rows[a]):    
                neigh = np.random.choice(tmp_A.rows[a])
                if not(forbidden_Matrix[a,neigh]):
                    nodes.append([a,neigh])
                    labels.append(1)

            if len(labels) >= batch_size:
                yield torch.LongTensor(nodes), torch.LongTensor(labels)
                del nodes[:]
                del labels[:]
    else:
        while True:
            a = random.randint(0,nodeNum-1)
            b = random.randint(0,nodeNum-1)
            nodes.append([a,b])
            if tmp_A[a,b]:
                labels.append(1)
            else:
                labels.append(0)

            if len(tmp_A.rows[a]):    
                neigh = np.random.choice(tmp_A.rows[a])
                nodes.append([a,neigh])
                labels.append(1)

            if len(labels) >= batch_size:
                yield torch.LongTensor(nodes), torch.LongTensor(labels)
                del nodes[:]
                del labels[:]

In [60]:
data_loader = iter(get_train_data(a_train, int(x_train.shape[0] *0.2),np.vstack((test_edges,val_edges)),True))

In [61]:
data_loader

<generator object get_train_data at 0x000001E00C0E5C48>

In [62]:
import random

In [63]:
inputs, labels = next(data_loader)

In [64]:
inputs , labels

(tensor([[2542,  277],
         [2112,   95],
         [1537,  269],
         ...,
         [1791, 2365],
         [1546, 2121],
         [1546, 1611]]),
 tensor([0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
         0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
         0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
         0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
         0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
         0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
         1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
         0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
         0, 1, 0, 1, 0, 0, 1, 0, 1, 

In [65]:
inputs , labels = next(data_loader)
len(inputs)

564

In [66]:
labels

tensor([0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
        1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
        1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,

In [67]:
op , oq = next(data_loader)

In [68]:
op , oq

(tensor([[ 974, 2722],
         [2660,  216],
         [1117, 1447],
         ...,
         [1072, 1431],
         [1049, 1393],
         [1049, 2426]]),
 tensor([0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
         1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
         0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
         0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
         0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
         0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
         0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
         1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
         0, 1, 0, 0, 1, 0, 1, 0, 0, 

In [69]:
v = a_train.tolil()

In [70]:
v.rows[0]

[549]

In [71]:
int(0.2 * 2824)

564

In [72]:
inputs,labels=next(data_loader)
len(inputs)

565

In [73]:
class Data:
    x = None
    edge_index =None
    anchorset_id = None
    dists_max = None
    dists_argmax = None
    dists = None
    def __init__(self, x, edge_index, dists_max = None, dists_argmax = None, dists = None):
        self.x = x
        self.edge_index = edge_index
        self.dists_max = dists_max
        self.dists_argmax = dists_argmax
    def copy(self):
        return Data(self.x, self.edge_index,
                    self.dists_max if not self.dists_max is None else None,
                    self.dists_argmax if not self.dists_argmax is None else None,
                    self.dists if not self.dists is None else None)

In [74]:
def convert_sSp_tSp(x):
    coo = x.tocoo()
    values = coo.data
    indices = np.vstack((coo.row, coo.col))
    i = torch.LongTensor(indices)
    v = torch.FloatTensor(values)
    shape = coo.shape
    return torch.sparse.FloatTensor(i, v, torch.Size(shape))

In [75]:
data = Data(convert_sSp_tSp(x_train).to_dense().to('cpu'), torch.LongTensor(train_ones.T).to('cpu'))

In [76]:
L = x_train
coo = L.tocoo()
values = coo.data
indices = np.vstack((coo.row, coo.col))
i = torch.LongTensor(indices)
v = torch.FloatTensor(values)
shape = coo.shape
torch.sparse.FloatTensor(i, v, torch.Size(shape)).to_dense().to('cpu')

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [77]:
train_ones.T

array([[1171, 1368, 1205, ..., 2762, 2816, 2819],
       [2018, 2557, 2399, ..., 2784, 2817, 2820]])

In [78]:
coo.toarray()[0,3647]

1.0

In [79]:
indices

array([[   0,    0,    0, ..., 2823, 2823, 2823],
       [3647, 3548, 3502, ...,  223,  169,   87]])

In [80]:
data

In [81]:
data.dists

In [82]:
val_edges

array([[2016, 2018],
       [1242, 2753],
       [1747, 2020],
       ...,
       [2142, 1823],
       [2143, 1026],
       [2144, 1908]], dtype=int64)

In [83]:
val_edges[:,0]

array([2016, 1242, 1747,   52,  663,  326,  923,   24,  724, 1805,  810,
        558, 1260, 1426, 2238, 1205, 2110, 1568, 1197,  609,  745,  435,
       2104, 1205,   39,  394,  388,  236,  149, 1120,   96, 1147,  880,
        950,  663,  388, 1882, 1408,  124,  663,  122, 1205, 1212, 1751,
       1205, 1990,   86,  132,   88, 1326, 1964, 1084,  756,  135,  201,
       2196,   22,  610,  160,  516,   18,  929, 2181,  884,  729,  236,
        895, 1287,  135,  318, 1709, 1226, 2303,  737,  579,  766,  202,
         42, 1225,  663,  429, 1467, 1412,  792, 1993, 1927, 1964,  675,
        538, 1039, 1410, 2498, 2152,  495, 1615, 1591, 1278, 1670,  964,
        139, 1552,  868, 1962, 2012,  579, 2264,  555,  863, 1735, 2123,
       1710,  165,  850,  824,   39,   15, 1212,  141,  663,  584,  956,
       1205,   67,  122, 2120,  137, 1315, 1426,  196,   24,  476, 1858,
       1671,  412,  200,  363, 1198,   74, 2659, 1371, 1050,  773,  542,
       1506, 1326,  950,  747,  798, 1340,   15,  9

In [84]:
import pickle

In [85]:
dd = pickle.load(open('dists-1.dat','rb'))

In [86]:
dd,dd.shape

(tensor([[1.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 1.0000, 0.0000,  ..., 0.1667, 0.0000, 0.0000],
         [0.0000, 0.0000, 1.0000,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.1667, 0.0000,  ..., 1.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 1.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 torch.Size([3327, 3327]))

In [87]:
dd[1800][876]

tensor(0.)

In [88]:
op , oq

(tensor([[ 974, 2722],
         [2660,  216],
         [1117, 1447],
         ...,
         [1072, 1431],
         [1049, 1393],
         [1049, 2426]]),
 tensor([0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
         1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
         0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
         0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
         0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
         0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
         0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
         1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
         0, 1, 0, 0, 1, 0, 1, 0, 0, 

In [89]:
op[7]

tensor([1086, 2319])

In [90]:
'''
tm = 1632
for i in range(dd.shape[0]):
    if i==tm:
        for j in range(dd.shape[1]):
            if dd[i][j] != 0.0:
                print(str(i) + ',' + str(j) + '==>' + str(dd[i][j]))
'''

"\ntm = 1632\nfor i in range(dd.shape[0]):\n    if i==tm:\n        for j in range(dd.shape[1]):\n            if dd[i][j] != 0.0:\n                print(str(i) + ',' + str(j) + '==>' + str(dd[i][j]))\n"

In [91]:
inputs,labels=next(data_loader)

In [92]:
inputs,labels=next(data_loader)
for i in range(inputs.shape[0]):
    if inputs[i][0] == 0 and inputs[i][1] == 628:
        print(True)

In [93]:
a_train.toarray()[1632][2496]

1.0

In [94]:
inputs,labels

(tensor([[1474,  827],
         [ 151, 2444],
         [ 151, 1612],
         ...,
         [ 911, 2576],
         [1796, 2240],
         [1796, 2031]]),
 tensor([0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
         1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
         1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
         0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
         0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
         0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 0, 1, 0, 

In [95]:
A.toarray()[1][10]

0.0

In [96]:
check_edge(0,628,val_zeros)

False

In [97]:
A

<3327x3327 sparse matrix of type '<class 'numpy.float64'>'
	with 4552 stored elements in Compressed Sparse Row format>

In [98]:
def check_edge_in_(v1,v2):
    if a_train.toarray()[v1][v2] == 1.0:
        return
    else:
        print(False)

In [99]:
print(a_train[2018][0])

In [100]:
#for i in range(val_zeros.shape[0]):
#    check_edge_in_(val_zeros[i][0],val_zeros[i][1])

In [101]:
len(nodes_hides)

503

In [102]:
nodes_hides

array([   2,   23,   25,   37,   45,   55,   56,   70,   72,   88,  107,
        112,  115,  125,  148,  161,  169,  173,  174,  177,  185,  192,
        193,  215,  221,  223,  226,  234,  240,  243,  252,  267,  276,
        280,  293,  294,  312,  325,  339,  341,  355,  358,  359,  362,
        365,  384,  398,  410,  420,  436,  446,  450,  453,  468,  474,
        478,  485,  489,  492,  496,  498,  511,  519,  526,  540,  546,
        549,  555,  559,  563,  572,  576,  582,  583,  586,  592,  603,
        613,  625,  647,  655,  656,  665,  676,  677,  679,  708,  719,
        722,  737,  738,  747,  760,  768,  769,  783,  785,  787,  789,
        794,  798,  805,  814,  821,  822,  827,  828,  831,  834,  838,
        843,  845,  848,  855,  856,  861,  864,  870,  872,  880,  883,
        892,  896,  898,  899,  905,  908,  909,  910,  913,  922,  926,
        930,  937,  939,  944,  949,  957,  965,  967,  973,  979,  983,
       1006, 1014, 1015, 1024, 1025, 1028, 1029, 10

In [103]:
len(nodes_keep)

2824

In [104]:
a_train

<2824x2824 sparse matrix of type '<class 'numpy.float64'>'
	with 3663 stored elements in Compressed Sparse Row format>

In [105]:
3327-2824

503

In [106]:
a_train.toarray()[1205][2399]

1.0

In [107]:
train_ones

array([[1171, 2018],
       [1368, 2557],
       [1205, 2399],
       ...,
       [2762, 2784],
       [2816, 2817],
       [2819, 2820]])

In [108]:
#draw networkx graph of 

In [109]:
import networkx as nx

In [110]:
inputs,labels

(tensor([[1474,  827],
         [ 151, 2444],
         [ 151, 1612],
         ...,
         [ 911, 2576],
         [1796, 2240],
         [1796, 2031]]),
 tensor([0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
         1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
         1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
         0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
         0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
         0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
         1, 0, 1, 0, 1, 0, 0, 1, 0, 

In [111]:
dd.shape

torch.Size([3327, 3327])

In [112]:
inputs

tensor([[1474,  827],
        [ 151, 2444],
        [ 151, 1612],
        ...,
        [ 911, 2576],
        [1796, 2240],
        [1796, 2031]])

In [113]:
edge_index = inputs

In [114]:
edge_list = edge_index.transpose(1,0).tolist()

In [115]:
import networkx as nx

In [116]:
graph = nx.Graph()

In [117]:
edge_list = inputs

In [118]:
graph.add_edges_from(edge_list)

In [119]:
nodes = []
for i in range(len(edge_list)):
    nodes.append(edge_list[i][0])
    nodes.append(edge_list[i][1])

nodes = list(set(nodes))

In [120]:
num_nodes = len(nodes)

In [121]:
n = num_nodes

In [122]:
n

1128

In [123]:
dists_array = np.zeros((n, n))


In [124]:
inputs

tensor([[1474,  827],
        [ 151, 2444],
        [ 151, 1612],
        ...,
        [ 911, 2576],
        [1796, 2240],
        [1796, 2031]])

In [125]:
import multiprocessing as mp

In [126]:
dists_dict = all_pairs_shortest_path_length_parallel(graph,cutoff=None)

NameError: name 'all_pairs_shortest_path_length_parallel' is not defined

In [ ]:
for i, node_i in enumerate(graph.nodes()):
            shortest_dist = dists_dict[node_i]
            for j, node_j in enumerate(graph.nodes()):
                dist = shortest_dist.get(node_j, -1)
                if dist!=-1:
                    # dists_array[i, j] = 1 / (dist + 1)
                    dists_array[node_i, node_j] = 1 / (dist + 1)

In [ ]:
def single_source_shortest_path_length_range(graph, node_range, cutoff):
    dists_dict = {}
    for node in node_range:
        dists_dict[node] = nx.single_source_shortest_path_length(graph, node, cutoff)
    return dists_dict

In [ ]:
def merge_dicts(dicts):
    result = {}
    for dictionary in dicts:
        result.update(dictionary)
    return result

In [ ]:
def all_pairs_shortest_path_length_parallel(graph,cutoff=None,num_workers=4):
    nodes = list(graph.nodes)
    random.shuffle(nodes)
    if len(nodes)<50:
        num_workers = int(num_workers/4)
    elif len(nodes)<400:
        num_workers = int(num_workers/2)

    pool = mp.Pool(processes=num_workers)
    results = [pool.apply_async(single_source_shortest_path_length_range,
            args=(graph, nodes[int(len(nodes)/num_workers*i):int(len(nodes)/num_workers*(i+1))], cutoff)) for i in range(num_workers)]
    output = [p.get() for p in results]
    dists_dict = merge_dicts(output)
    pool.close()
    pool.join()
    return dists_dict

In [ ]:
Gh = nx.Graph()

In [ ]:
Gh.add_edge(1,5)
Gh.add_edge(1,2)
Gh.add_edge(2,5)
Gh.add_edge(2,4)
Gh.add_edge(4,6)
Gh.add_edge(2,3)
Gh.add_edge(4,7)
Gh.add_edge(4,8)
Gh.add_edge(7,8)
Gh.add_edge(8,9)

In [ ]:
L = nx.single_source_shortest_path_length(Gh,8)

In [ ]:
L

In [ ]:
#basically apply the above function to nodes pairs in upper triangular matrix 

dist_dict = np.zeros((n,n))

for i in range(dist_dict.shape[0]):
    for j in range(dist_dict.shape[0]):
        if i < j:
            L = nx.single_source_shortest_path_length(Gh,)

In [ ]:
import numpy as np

In [ ]:
nodes_in_network = [0,1,2,3,4,5,6]

edge_list = [
    [0,1],
    [0,3],
    [1,4],
    [2,3],
    [0,4],
    [5,6]
]


In [ ]:
tg = nx.Graph()
tg.add_edges_from(edge_list)

In [ ]:
nx.write_gexf(tg,"dist_graph.gexf")

In [ ]:
dist_M = np.identity(len(nodes_in_network))

In [ ]:
dist_M

In [ ]:
nodes_in_edge = []
for i in range(len(edge_list)):
    nodes_in_edge.append(edge_list[i][0])
    nodes_in_edge.append(edge_list[i][1])

nodes_in_edge = list(set(nodes_in_edge))

In [ ]:
for node in range(dist_M.shape[0]):
    if node in nodes_in_edge:
        L = nx.single_source_shortest_path_length(tg,node)
        
        if len(L) > 0:
            for key in L.keys():
                if node != key:
                    dist_M[node][key] = L[key]

In [ ]:
dist_M

In [ ]:
for i in range(dist_M.shape[0]):
    for j in range(dist_M.shape[1]):
        if i!=j and dist_M[i][j]!=0:
            dist_M[i][j] = float("{0:.2f}".format((1/(dist_M[i][j]+1))))

In [ ]:
dist_M

In [127]:
A

<3327x3327 sparse matrix of type '<class 'numpy.float64'>'
	with 4552 stored elements in Compressed Sparse Row format>

In [128]:
test_edges

array([[   2, 3285],
       [  12,  677],
       [  12,  794],
       ...,
       [3287, 1287],
       [3313,  888],
       [3316, 1874]], dtype=int64)

In [129]:
test_ones

array([[   2, 3285],
       [  12,  677],
       [  12,  794],
       ...,
       [3146, 3147],
       [3228, 3236],
       [3286, 3287]], dtype=int64)

In [131]:
for i in range(test_zeros.shape[0]):
    if A.toarray()[test_zeros[i][0]][test_zeros[i][1]] == 1:
        print("false")

In [132]:
len(test_edges)

2873

In [134]:
len(test_ones)

889

In [136]:
2873 - 889

1984

In [137]:
1984/4552

0.4358523725834798

In [135]:
889/4552

0.195298769771529

In [138]:
val_ones

array([[2016, 2018],
       [1242, 2753],
       [1747, 2020],
       [  52, 1205],
       [ 663, 1917],
       [ 326, 1678],
       [ 923, 1135],
       [  24, 1709],
       [ 724, 1506],
       [1805, 1933],
       [ 810, 2021],
       [ 558, 2182],
       [1260, 1789],
       [1426, 2084],
       [2238, 2553],
       [1205, 1749],
       [2110, 2210],
       [1568, 1615],
       [1197, 2010],
       [ 609, 1425],
       [ 745, 2795],
       [ 435, 1371],
       [2104, 2400],
       [1205, 2256],
       [  39, 1489],
       [ 394, 2259],
       [ 388, 2303],
       [ 236, 2231],
       [ 149, 2381],
       [1120, 2389],
       [  96, 1858],
       [1147, 1553],
       [ 880, 1747],
       [ 950, 2147],
       [ 663,  766],
       [ 388, 2301],
       [1882, 2250],
       [1408, 2036],
       [ 124,  938],
       [ 663,  783],
       [ 122, 1642],
       [1205, 1919],
       [1212, 1375],
       [1751, 2182],
       [1205, 2397],
       [1990, 1991],
       [  86,  118],
       [ 132,

In [140]:
a_train

<2824x2824 sparse matrix of type '<class 'numpy.float64'>'
	with 3663 stored elements in Compressed Sparse Row format>

In [143]:
for i in range(val_zeros.shape[0]):
    if a_train.toarray()[val_zeros[i][0]][val_zeros[i][1]] == 1:
        print("false")

In [144]:
len(val_zeros) / 3663

0.1001911001911002

In [145]:
len(val_zeros) , len(val_ones)

(367, 367)

In [146]:
val_zeros

array([[   0, 1315],
       [   6,  597],
       [  11, 2319],
       [  13,  437],
       [  26, 2751],
       [  40,   94],
       [  43,  577],
       [  47,  772],
       [  48, 2023],
       [  52,  455],
       [  54, 2209],
       [  58, 1238],
       [  59, 1498],
       [  62, 1477],
       [  67, 1592],
       [  73, 2632],
       [  75, 2025],
       [  77,  700],
       [  80, 1187],
       [  80, 2558],
       [  81,  645],
       [  84,   90],
       [ 103,   99],
       [ 105, 2735],
       [ 106,  754],
       [ 107,  504],
       [ 108,  456],
       [ 119, 2362],
       [ 121, 1323],
       [ 123, 2555],
       [ 126, 2120],
       [ 127,   13],
       [ 131, 1980],
       [ 145, 1776],
       [ 145, 2685],
       [ 163, 1214],
       [ 164, 2474],
       [ 176, 1425],
       [ 187, 2438],
       [ 198, 2170],
       [ 228,  850],
       [ 231, 1943],
       [ 236, 1244],
       [ 250, 1179],
       [ 251,  932],
       [ 254,  459],
       [ 254, 1171],
       [ 255,